# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa2b917f5354322605e24505e11dbd2acaca86bee5cdb5f38ed5ee830b9d04ecb599dd2be07a862d091fa4b130a64160f352b0f6bdc31afefd8bbd4bb3781e1

test:
  secret_key_base: 3611b7aaf668bfd34e50e74e88a7615ac521a0f1534183da1fa942214c3bbfb9ac71e9c8ab2adf6f157ed206253efaec39f5295d2d8cb982fbc5342b060babf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
